language: python
python:
  - '2.6'
  - '2.7'
  - '3.5'
# command to install dependencies
install:
  - pip install WindAdapter
  - pip install coveralls
# command to run tests
script:
  - coverage run --source=argcheck setup.py tests
after_success:
  - coveralls