language: python
python:
  - '2.6'
  - '2.7'
  - '3.5'
# command to install dependencies
install:
  - pip install coveralls
  - python setup.py install
# command to run tests
script:
  - trail argcheck
after_success:
  - coveralls
